server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true
  liquibase:
    change-log: liquibase/liquibase-changeLog.xml
    enabled: true
    contexts: schema, test-data

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/index.html

logging:
  level:
    root: info
    kg.rinat: debug
